# Generated by Django 3.1.6 on 2021-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('parent', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
