# Generated by Django 3.1.6 on 2021-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('uid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('parent', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
